- name: Deployment via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: ${{ secrets.SSH_PORT }}
    timeout: 60s
    command_timeout: 10m
    debug: true
    script_stop: true
    script: |
      whoami
      pwd
      cd /home/eduwhistle-gscsite/htdocs/gscsite.eduwhistle.com/gsc-next
      ls -la
      chmod +x deploy.sh
      ./deploy.sh
